<a href="https://colab.research.google.com/github/jesiqueira/Pandas_visualizar_dados_acoes/blob/master/Visualizar_dados_Acoes_com_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Carregar Pandas e base de dados criado com web scraping

In [1]:
# Importar Pandas
import pandas as pd

In [13]:
# Carregar base de dados
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dados/dados_acoes.csv', encoding='UTF-8', sep=';')

In [14]:
# Visualizar 5 linhas
df.head()

              empresa  papel                    setor  ...  ebita  margin bruta   dy
0           ATMASA ON  ATMP3        Serviços Diversos  ...   1.52          1.8%  0.0
1         ASSAI ON NM  ASAI3  Comércio e Distribuição  ...   7.32         16.4%  0.0
2  JULIO SIMOES ON NM  JSLG3               Transporte  ...  17.63         10.7%  1.1
3  CSNMINERACAO ON N2  CMIN3                Mineração  ...   6.85         60.3%  0.0
4   ELETROMIDIA ON NM  ELMD3                    Mídia  ...   0.00             -  0.0

[5 rows x 13 columns]

In [15]:
# Visualizar tamanho do arquivo
df.shape

(252, 13)

In [36]:
# Ordenar por empresa
df.sort_values('papel', ascending=True).head()

              empresa  papel                    setor  ...  ebita  margin bruta   dy
183      ALLIAR ON NM  AALR3  Análises e Diagnósticos  ...  50.25         16.4%  1.0
25        AERIS ON NM  AERI3  Máquinas e Equipamentos  ...  44.29         11.1%  0.0
251     AFLUENTE T ON  AFLT3         Energia Elétrica  ...  29.48         64.8%  8.1
94   BRASILAGRO ON NM  AGRO3             Agropecuária  ...   9.69         30.8%  2.4
43      ESTAPAR ON NM  ALPK3        Serviços Diversos  ...  17.23         25.4%  0.0

[5 rows x 13 columns]

In [29]:
# Realizando Filtro 
df[(df.pl >= 5) & (df.pl <=20) & (df.dy >= 5) & (df.dy <= 25) & (df.cotacao >= 4) & (df.cotacao <= 25)]

                         empresa   papel  ... margin bruta    dy
62   Direcional Engenharia ON NM   DIRR3  ...        34.6%   6.5
72                  SMILES ON NM   SMLS3  ...        82.7%   5.5
78             WHIRLPOOL S.A. PN   WHRL4  ...        18.6%  17.1
79             WHIRLPOOL S.A. ON   WHRL3  ...        18.6%  17.3
89       CYRELA BRAZIL REALTY PN   CYRE3  ...        32.5%   7.5
93                   CAMIL ON NM   CAML3  ...        23.2%   5.1
118             BANRISUL S/A PNB   BRSR6  ...            -   5.3
175               ENAUTA PART ON   ENAT3  ...        33.4%   6.9
234           AES TIETE E UNT N2  TIET11  ...        94.4%   6.6
239                  TAESA PN N2   TAEE4  ...        70.6%   9.7
240                  TAESA ON N2   TAEE3  ...        70.6%   9.7
249                  CEMIG PN N1   CMIG4  ...        23.1%   5.0

[12 rows x 13 columns]

In [28]:
df[df.papel == 'WHRL4']

              empresa  papel                  setor  ...  ebita  margin bruta    dy
78  WHIRLPOOL S.A. PN  WHRL4  Utilidades Domésticas  ...  15.56         18.6%  17.1

[1 rows x 13 columns]